
The file is a more in-depth look at decision trees and how they work. I am using the         dataset from scikit! 


> Link to the video <br>
> https://www.youtube.com/watch?v=tNa99PG8hR8

> For the graph I used pydot

! pip3 install pydot

! pip3 install scikit-learn

In [9]:
from sklearn.datasets import load_iris
import numpy as np
from sklearn import tree
# from sklearn.externals.six import StringIO
# import pydot 

In [11]:
iris = load_iris()

In [12]:
"""
    feature_names : describe what features per flower
    data[0] : the value of the feature for flower at index 0
"""
print(iris.feature_names)
print(iris.data[0])


"""
    target_names : showcases some name from the dataset
    target[0] : the name of the flower at index 0 - The LABEL
"""
print(iris.target_names)
print(iris.target[60])



['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[5.1 3.5 1.4 0.2]
['setosa' 'versicolor' 'virginica']
1


In [13]:
# Looking at all the data
print("Label\t", iris.feature_names)
print("====================================================================================================")

for i in range(len(iris.target)):
    if iris.target[i] == 0: 
        print("setosa \t", iris.data[i])
    elif iris.target[i] == 1:
        print("versicolor \t", iris.data[i])
    else:
        print("virginica \t", iris.data[i])


Label	 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
setosa 	 [5.1 3.5 1.4 0.2]
setosa 	 [4.9 3.  1.4 0.2]
setosa 	 [4.7 3.2 1.3 0.2]
setosa 	 [4.6 3.1 1.5 0.2]
setosa 	 [5.  3.6 1.4 0.2]
setosa 	 [5.4 3.9 1.7 0.4]
setosa 	 [4.6 3.4 1.4 0.3]
setosa 	 [5.  3.4 1.5 0.2]
setosa 	 [4.4 2.9 1.4 0.2]
setosa 	 [4.9 3.1 1.5 0.1]
setosa 	 [5.4 3.7 1.5 0.2]
setosa 	 [4.8 3.4 1.6 0.2]
setosa 	 [4.8 3.  1.4 0.1]
setosa 	 [4.3 3.  1.1 0.1]
setosa 	 [5.8 4.  1.2 0.2]
setosa 	 [5.7 4.4 1.5 0.4]
setosa 	 [5.4 3.9 1.3 0.4]
setosa 	 [5.1 3.5 1.4 0.3]
setosa 	 [5.7 3.8 1.7 0.3]
setosa 	 [5.1 3.8 1.5 0.3]
setosa 	 [5.4 3.4 1.7 0.2]
setosa 	 [5.1 3.7 1.5 0.4]
setosa 	 [4.6 3.6 1.  0.2]
setosa 	 [5.1 3.3 1.7 0.5]
setosa 	 [4.8 3.4 1.9 0.2]
setosa 	 [5.  3.  1.6 0.2]
setosa 	 [5.  3.4 1.6 0.4]
setosa 	 [5.2 3.5 1.5 0.2]
setosa 	 [5.2 3.4 1.4 0.2]
setosa 	 [4.7 3.2 1.6 0.2]
setosa 	 [4.8 3.1 1.6 0.2]
setosa 	 [5.4 3.4 1.5 0.4]
setosa 	 [5.2 4.1 1.5 0.1]
setosa 	 [5.5 4.2 1

In [14]:
# Splitting up the dataset! IMPORTANT

# A list that holds the index of obj to remove.
test_idx = [0,50,100]

"""
Training data: 

Here I am removing 3 items from the target (label) and feature dataset at a very specific index.
    1. I will take the 3 removed and use them as my testing data. 
    2. I will take the rest as training data.

"""

# Removing the index 0, 50, & 100 from the target dataset & feature dataset
train_label = np.delete(iris.target, test_idx)
train_feature_data = np.delete(iris.data, test_idx, axis=0)


# Creating the testing list with the 3 obj removed from the dataset.
test_label = iris.target[test_idx]
test_feature_data = iris.data[test_idx]



print("My testing targets \n", test_label)
print("\nMy testing feature data \n", test_feature_data)
len(test_feature_data)


My testing targets 
 [0 1 2]

My testing feature data 
 [[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]]


3

In [15]:
# Creating my tree
clf = tree.DecisionTreeClassifier()

# Using the training sets
clf = clf.fit(train_feature_data, train_label)


# Here I am predicting the flowers using the test features from the list 'test_feature_data'
pred = clf.predict(test_feature_data)


# Printing out the retrun of the predict function. adding the label here manually.
for label in pred:
    if label == 0: 
        print("setosa")
    elif label == 1:
        print("versicolor")
    else:
        print("virginica")

setosa
versicolor
virginica


In [16]:
# conda is having a tough time install pydot, for now running it in the terminal seems to work, not in vscode.

# dot_data = StringIO()
# tree.export_graphviz(clf,
#                         out_file=dot_data,
#                         feature_names=iris.feature_names,
#                         class_names=iris.target_names,
#                         filled=True, rounded=True,
#                         impurity=False)
# graph = pydot.graph_from_dot_data(dot_data.getvalue())
# graph[0].write_pdf("iris.pdf") 

In [19]:
print(test_feature_data[0], test_label[0])
print(iris.target_names,"\n",iris.feature_names)

[5.1 3.5 1.4 0.2] 0
